package com.rice.bohai.model

import java.io.Serializable

data class PintuanProduceModel(
    var id: Int = 0,
    var product_type_id: Int = 0,
    var product_type_name: String = "",
    var price: String = "",
    var no_number: String = "",
    var created_at: String = "",
    var updated_at: String = "",
    var status: Int = 0,
    var is_delele: Int = 0,
    var detail: String = "",
    var name: String = "",
    var image: String = "",
    var order_num: Int = 0,
    var status_name: String = "",
    var transaction_number: Int = 0,
    var unit: String = "",
    var weight: String = "",
    var imageList: List<String> = listOf(),
    var is_start_lock: Int = 0,
    var is_start_reward: Int = 0,
    var reward_percent: Int = 0,
    var freed_lock_num: Int = 0,
    var formalities_percent: Int = 0,
    var day_trade_volume: Int = 0,
    var is_start_pick_up: String = "",
    var pick_up_price: String = "",
    var profit: String = "",
    var lock_number: Int = 0,
    var number: Int = 0,
    var freed_price: String = "",
    var buy_price: String = "",
    var buy_total_price: Int = 0,
    var sea_product_id: String = "",
    var pick_up_prev_price: String = "",
    var synchronization_order_num: Int = 0,
    var is_start_synchronization: Int = 0,
    var out_price: String = "",
    var repair_pick_up_reward: String = "",
    var buy_product_id: Int = 0,
    var freed_product_id: Int = 0,
    var freed_day_number: Int = 0,
    var freed_day_last_number: Int = 0,
    var is_change_valid: String = ""
) : Serializable